default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
development:
  <<: *default
  adapter: postgresql
  database: makersbnb
test:
  <<: *default
  adapter: postgresql
  database: makersbnb_test
